### ISSUE TITLE
OK program but it randomly deleted everything

### ISSUE THREAD

**Issue by fitzyjay** [topeterk/HitCounterManager#9] opened 2018-10-17 15:37 UTC
Really don't know what else to say. I did not alter any of the files of this program, yet today every single split is gone. Even the pre-built splits the app comes with. I'm honestly fucking dumbfounded. 

Making the splits again isn't that much work but the fact that I lost my PB and this all might happen again is a huge deterrent to using this program further.

Using a windows capture blows but at least hit counter websites do not randomly delete every single thing you have done.

**Comment by topeterk** [comment] 2018-10-17 17:03
This is the first time I hear about this. Have you checked the content of the XML file that holds the data? Is it empty, non XML-compliant or was it moved/deleted?

Any idea, what you mean with "randomly", so when do you think this might have happened?
The application accesses the XML on startup to read the stored splits once and it saves the XML on closing the application or pressing the save button.
So maybe either during the saving process the file couldn't be written correctly or you encountered a bug that will let the software write wrong data intentionally.

The XML file that is holding your data is (in the currently released versions) the same file that has the initial pre-built splits. If someone wants to reset the software, one can replace the XML with the original one from the ZIP or reinstall the software. Therefore there was no use case to keep the initial splits available afterwards.
However new versions will have these initial splits in a separate file but the reason for this is that upgrading the software will not overwrite existing splits from the user by mistake.

**Comment by fitzyjay** [comment] 2018-10-17 17:14
I checked the XML file and it looked like it still had all the pre built splits. I'm a programming/software illiterate, so a bunch of it I didn't understand. But I did see BB, DS1, 2 and 3 bosses in a format which seemed like they were the pre built splits. But I didn't see any of my previously saved splits, and the program had neither mine or the prebuilt splits in the actual Hit Counter Manager application

**Comment by topeterk** [comment] 2018-10-17 17:33
When you still have the XML file, can you try to ZIP it and add it to this issue here? [HowTo](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/)
Maybe I can figure some more details how this happened or what happened in detail.

Has this issue happened only once our can you reproduce it in any kind of way?

**Comment by topeterk** [comment] 2018-10-24 17:59
As I already mentioned, there were already some improvements to avoid mistakenly wiped saves on updating the software.
Additionally I added a user questions if the application shall save the profiles when the application closes. This should also prevent most unwanted changes from overwriting the save file.
So maybe you have a look at [version 1.14](https://github.com/topeterk/HitCounterManager/releases/tag/1.14.0.0) that should do better in this respect.
If you can reproduce and narrow down this issue in more detail, please let me know that I can hopefully fix it with the next version but in the meantime I'm closing this issue here.

**Closed by topeterk** 2018-10-24 17:59 UTC
